- .idea/.gitignore
- .idea/devcourse-project-1.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-test.yml
- backend/src/main/resources/application.yml
> config: StandardApplicationYmlSetting

- backend/build.gradle.kts
- backend/src/main/java/com/back/global/app/AppConfig.java
- backend/src/main/java/com/back/global/exception/ServiceException.java
- backend/src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
- backend/src/main/java/com/back/global/jpa/entity/BaseEntity.java
- backend/src/main/java/com/back/global/rsData/RsData.java
- backend/src/main/java/com/back/global/standard/util/Ut.java
> domain and global

- backend/src/main/java/com/back/domain/product/product/entity/Product.java
- backend/src/main/java/com/back/domain/product/productImage/entity/ProductImage.java
> feat: ProductImage 엔티티 추가

- .idea/modules/back.iml
- backend/src/main/java/com/back/domain/wishList/WishList.java
gitignore 설정이 계속 충돌나서 브랜치 다시 파서 만들었습니다.
> feat:wishList 구현

- frontend/src/app/login/page.tsx
- frontend/src/app/orderHistory/page.tsx
- frontend/src/app/signup/page.tsx
> feat:주문내역페이지 UI구현(기능구현X)

- frontend/src/app/order/page.tsx
- frontend/src/app/page.tsx
> feat:메인페이지와 주문페이지에 찜 목록 UI구현(기능구현X)

- frontend/src/app/admin/page.tsx
- frontend/src/app/layout.tsx
- frontend/src/app/page.tsx
> 관리자페이지 UI구현(회원정보 조회, 상품 관리)

- backend/src/main/java/com/back/domain/product/product/controller/ApiV1AdmProductController.java
- backend/src/main/java/com/back/domain/product/product/controller/ApiV1ProductController.java
- backend/src/main/java/com/back/domain/product/productImage/controller/ApiV1AdmProductImageController.java
- backend/src/main/java/com/back/domain/product/productImage/controller/ApiV1ProductImageController.java
- backend/src/main/java/com/back/global/rq/Rq.java
- backend/src/main/java/com/back/global/security/SecurityConfig.java
- backend/src/test/java/com/back/domain/product/product/controller/ApiV1AdmProductControllerTest.java
- backend/src/test/java/com/back/domain/product/product/controller/ApiV1ProductControllerTest.java
- backend/src/test/java/com/back/domain/product/productImage/controller/ApiV1AdmProductImageControllerTest.java
- backend/src/test/java/com/back/domain/product/productImage/controller/ApiV1ProductImageControllerTest.java
> Enhancement#120

- frontend/src/app/layout.tsx
- frontend/src/app/login/page.tsx
> fix: 초기접속시 로그아웃상태유지위해 localStorage 대신에 sessionStorage 도입

- frontend/src/app/order/page.tsx
Close #117
상품목록에서 장바구니로 상품추가 기능구현
장바구니에서 상품수량조절 및 삭제기능 구현
총 금액 계산 기능 구현
로그인상태로 결제하기 버튼 클릭시 임시 창이 나타나도록 기능구현
로그아웃상태로 결제하기 버튼 클릭시 로그인 창으로 이동 기능 구현
> feat: 주문페이지 기능구현

- frontend/src/app/admin/page.tsx
- frontend/src/context/ProductContext.tsx
> feat: 상품관리추가수정내역 durability 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/order/page.tsx
- frontend/src/app/page.tsx
- frontend/src/context/ProductContext.tsx
> WishList 제품소개와 주문페이지 연동

- backend/src/test/java/com/back/domain/product/product/controller/ApiV1AdmProductControllerTest.java
> fix: 403 오류 메시지 수정

- frontend/src/app/order/page.tsx
> feat: wishlist가 비어있을때 메세지 출력 구현

- frontend/src/app/account/client/page.tsx
> feat: 일반회원정보 페이지 UI 및 수정기능 구현 사용자정보는 하드코딩

- backend/src/main/java/com/back/global/security/SecurityConfig.java
> fix: passwordEncoder 하나로

- frontend/src/app/products/detail/[id]/page.tsx
- frontend/src/app/products/page.tsx
> feat: 상세페이지 구현

- frontend/src/app/account/admin/accountManagement/page.tsx
- frontend/src/app/account/admin/productManagement/page.tsx
- frontend/src/app/order/page.tsx
- frontend/src/app/products/page.tsx
- frontend/src/context/ProductsContext.tsx
> feat: ProductsContext에 useContext 적용

- backend/src/main/java/com/back/domain/product/product/controller/ApiV1ProductController.java
- frontend/src/app/products/detail/[id]/page.tsx
> 제품상세페이지 주문페이지로 링크이동기능구현 및 이미지불러오기 오류수정

- frontend/src/app/products/page.tsx
> fix: 찜하기 버튼누르면 상세페이지로 이동하는 버그수정

- .gitignore
> fix: root디렉토리에서 db커밋막기위해 .gitignore생성

- frontend/src/app/account/admin/accountManagement/page.tsx
- frontend/src/app/login/page.tsx
- frontend/src/app/signup/page.tsx
> refactor: user관련페이지 ui개선

- frontend/src/app/login/page.tsx
- frontend/src/app/products/detail/[id]/page.tsx
- frontend/src/app/products/page.tsx
- frontend/src/app/signup/page.tsx
- frontend/src/lib/backend/apiV1/schema.d.ts
> fix: wishlist 커스텀 훅 관련 오류 해결, 기타 style 수정
